name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build (Linux)
      run: |
        sudo add-apt-repository --remove ppa:ubuntu-toolchain-r/test -y
        sudo apt update
        sudo env ACCEPT_EULA=Y apt upgrade
        sudo apt install gcc-multilib
    
        rustup target add i686-unknown-linux-gnu # Linux 32-bit
        rustup target add x86_64-unknown-linux-gnu # Linux 64-bit

        cargo build --release --target=i686-unknown-linux-gnu # 32-bit
        cargo build --release --target=x86_64-unknown-linux-gnu # 64-bit
    
    - name: Rename and Upload Artifacts
      run: |
        mkdir artifacts

        # Handle 32-bit Linux artifact
        cp target/i686-unknown-linux-gnu/release/crash.so artifacts/linux.dll
        
        # Handle 64-bit Linux artifact
        cp target/x86_64-unknown-linux-gnu/release/crash.so artifacts/gmsv_crash_linux(x64).dll
        
        ls artifacts # Optional: Verify the contents of the artifacts folder

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Build Artifacts
        path: artifacts/